service: DevScraperChronLambda

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    SECRET_ID: DevWebApiSecret
    LOGGING_ENABLED: true
    IS_OFFLINE: true

functions:
  startScraperChron:
    handler: dist/index.scraperChronHandler
    events:
      - http:
          path: start-scraper-chron
          method: post

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4002
