version: "3.8"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=user_local
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-tier
  scraper:
    image: scraper:latest
    depends_on:
      - postgres
    networks:
      - app-tier
volumes:
  postgres:


networks:
  app-tier:
    driver: bridge
