-- AlterTable
ALTER TABLE "AmazonSpApi" ADD COLUMN     "lastUsedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "lastUpdaterCallAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
